### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by tkymuk** [gregzaal/HDR-Merge#10]
I have added blender 2.79 to my blender folder and i have also installed Luminance hdr. I have referenced their location in exe_paths.json as

{
    "blender_exe": "C:\\Program Files\\Blender Foundation\\Blender-2.79\\blender.exe",
    "luminance_cli_exe": "C:\\Program Files\\Luminance HDR\\v.2.6.0\\luminance-hdr-cli.exe"
}

I have used RawTherapee 5.8 to create 16 bit tif files as instructed in the walkthrough.

when i run hdr_brackets the below pops up 

This window will report detailed progress of the blender renders.
Use the other window to start the merging process.
Starting...

Brackets: 8
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 914, in _bootstrap_inner
  File "C:\Python35\lib\threading.py", line 862, in run
  File "hdr_brackets.py", line 287, in real_execute
  File "hdr_brackets.py", line 287, in <listcomp>
  File "hdr_brackets.py", line 114, in ev_diff
ZeroDivisionError: division by zero

I have no experience with python so i dont know if what i am doing is incorrect, but i cant see any additional files being created in the folder ive set as the root folder for the tif files.

Paul.

**Comment by savva-zakharov** [comment]
Closed due to elapsed time
